#!/bin/bash

if [ "$#" -ne 1 ]; then
	echo "\e[31mYou're missing a commit message."
	echo "Usage: fastgit \"Commit message\""
	exit 1
fi

git add.
git commit -m "$1"
git pull --rebase origin
git push origin